theme: jekyll-theme-minimal
title: Auree Aubert
skill: Ruby, Go, Haskell, Continious Integration, Metaprogramming, PostgreSQL, MongoDB, Redis, UX, Design Thinking, State Machine, Sketch, Invision, Agile, Scrum
logo: /assets/img/profile_picture.jpg
description: French guy - 21yo - Product & Software Development
linkedin: https://www.linkedin.com/in/aureeaubert/
phone: "+33627881693"
google_analytics: UA-117250185-1
